// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chirps.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addChirp = `-- name: AddChirp :one
insert into 
  chirps (id, created_at, updated_at, body, uid)
values 
  ((select gen_random_uuid()), 
  (select now()),
  (select now()),
  $1, 
  $2)
returning id, created_at, updated_at, body, uid
`

type AddChirpParams struct {
	Body string
	Uid  uuid.UUID
}

func (q *Queries) AddChirp(ctx context.Context, arg AddChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, addChirp, arg.Body, arg.Uid)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Body,
		&i.Uid,
	)
	return i, err
}
