// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addUsersRefreshToken = `-- name: AddUsersRefreshToken :one
insert into 
  refresh_tokens (
    token, created_at, updated_at, user_id, expired_at
  )
values (
  ($1),
  (select now()),
  (select now()),
  $2,
  $3
) returning $1
`

type AddUsersRefreshTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiredAt time.Time
}

func (q *Queries) AddUsersRefreshToken(ctx context.Context, arg AddUsersRefreshTokenParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, addUsersRefreshToken, arg.Token, arg.UserID, arg.ExpiredAt)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserByRT = `-- name: GetUserByRT :one

select 
  u.id, u.created_at, u.updated_at, u.email, u.password, 
  refresh_tokens.revoked_at 
from 
  users u
inner join 
  refresh_tokens
  on refresh_tokens.user_id = u.id
where 
  refresh_tokens.token = $1
`

type GetUserByRTRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
	RevokedAt sql.NullTime
}

func (q *Queries) GetUserByRT(ctx context.Context, token string) (GetUserByRTRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByRT, token)
	var i GetUserByRTRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRT = `-- name: RevokeRT :exec

update 
  refresh_tokens
set
  updated_at = (select now()),
  revoked_at = (select now())
where
  token = $1
`

func (q *Queries) RevokeRT(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRT, token)
	return err
}
