// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
)

const addUser = `-- name: AddUser :one
insert into
  users (id, created_at, updated_at, email, password)
values (
  (select gen_random_uuid()), 
  (select now()), 
  (select now()), 
  $1,
  $2
)
returning id, created_at, updated_at, email, password
`

type AddUserParams struct {
	Email    string
	Password string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const reset = `-- name: Reset :exec

delete from users where id = id
`

func (q *Queries) Reset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, reset)
	return err
}
